name: Build and Release Inkpull Windows EXE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Get version from Metadata
        run: |
          import sys, os
          sys.path.insert(0, ".")
          from cli.app_metadata import Metadata
          
          version = Metadata.__version__
          print(f"Detected version: {version}")
          
          # Write version to GitHub environment file
          with open(os.environ['GITHUB_ENV'], 'a') as f:
              f.write(f"VERSION={version}\n")
        shell: python

      - name: Prepare build folders
        run: mkdir PYINSTALLER

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller ^
            -y ^
            --workpath PYINSTALLER\build ^
            --distpath PYINSTALLER\dist ^
            ".github\workflows\Inkpull.spec"

      - name: Package EXE with 7-Zip
        shell: cmd
        run: |
          cd PYINSTALLER\dist
            "C:\Program Files\7-Zip\7z.exe" a -t7z ..\..\Inkpull-${{ env.VERSION }}.7z * ..\..\LICENSE

      - name: Delete existing release and tag if version exists
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="inkpull-${{ env.VERSION }}"
      
          echo "Checking for existing release $VERSION"
      
          if gh release view "$VERSION" >/dev/null 2>&1; then
            echo "Existing release found. Deleting..."
            gh release delete "$VERSION" --yes
          else
            echo "No existing release found."
          fi
      
          if git tag -l "$VERSION" | grep -q "$VERSION"; then
            echo "Deleting local tag"
            git tag -d "$VERSION"
          fi
      
          echo "Deleting remote tag if it exists"
          git push --delete origin "$VERSION" || true


      - name: Create Release and upload artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: Inkpull-${{ env.VERSION }}.7z
          tag: inkpull-${{ env.VERSION }}
          name: Inkpull v${{ env.VERSION }}
          body: Automated Inkpull build
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
